#!/bin/bash

DEFAULT_USER=vanceza

PROGNAME=$(basename "$0")
usage(){
    echo "Usage: $PROGNAME [USER] REPOSITORY"
    exit 1;
}

case $# in
    1)
        USER=${DEFAULT_USER}
        REPO=$1
        ;;
    2)
        USER=$1
        REPO=$2
        ;;
    *)
        usage
esac

git clone git@bitbucket.org:${USER}/${REPO}.git
