#!/bin/bash
NAME="${1:-$NAME}"
DESCRIPTION="${2:-$DESCRIPTION}"

curl -i -X POST https://api.github.com/user/repos -u vanceza -d @- <<-EOF
  {
    "name":"$NAME",
    "description":"$DESCRIPTION"
  }
EOF
