#!/bin/bash
# Remember to install base-devel and wget
makeit () {
   if [ "$(whoami)" = "root" ]; then
     chown -R abs .
     sudo -u abs makepkg -si
   else
     makepkg -si
   fi
}

set -x -e
pacman -S --needed --noconfirm base-devel wget
if [ "$(whoami)" = "root" ]; then
    if [ "$(grep abs /etc/passwd)" = "" ]; then
        useradd -r abs || true
        echo "abs ALL=(ALL) NOPASSWD: /usr/bin/pacman" >>/etc/sudoers
    fi
fi

cd /tmp
wget https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar zxvf package-query.tar.gz
cd package-query
makeit
cd ..
wget https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar zxvf yaourt.tar.gz
cd yaourt
makeit
cd ..
rm package-query.tar.gz
rm -r package-query
rm yaourt.tar.gz
rm -r yaourt

