#!/bin/python3
"""
Open a "mailto:" link

Takes one argument of the form
    mailto:me@mail.com?subject=mysubject&body=mybody
Opens in a browser the URL
    https://webmail.za3k.com/?_task=mail&_action=compose&_to=me@mail.com&_subject=mysubject&_message=mybody

To set this as your program to open mailto links, first run:
    sudo mailto-opener --install
And then fully close any browser you want it to work in (really).
"""
import pwd, grp
import os, sys
from subprocess import check_output, run
from collections import defaultdict

# Valid mailto keys are: to, subject, body, cc, bcc
# The below is for my Roundcube instance
WEBMAIL_URL="https://webmail.za3k.com/?_task=mail&_action=compose&_to={to}&_subject={subject}&_message={body}"

DEFAULT_BROWSER="xdg-open"
DESKTOP="""
[Desktop Entry]
Type=Application
Name=mailto: link opener (github.com/za3k/short-programs)

# The executable of the application, possibly with arguments.
Exec={BIN} %u
"""

def run_without_root(args):
    run(
        ["sudo", 
            "-u", "#"+os.environ.get("SUDO_UID"),
            "-g", "#"+os.environ.get("SUDO_GID")]+
        args
    )

def usage():
    print(__doc__.strip())

def install():
    binary = os.path.abspath(__file__)
    #myname = sys.argv[0].split("/")[-1]
    DESKTOP_NAME = "mailto-opener.desktop"
    DESKTOP_PATH = os.path.join("/usr/local/share/applications", DESKTOP_NAME)
    with open(DESKTOP_PATH, "w") as f:
        f.write(DESKTOP.format(BIN=binary))
    run(["desktop-file-validate", DESKTOP_PATH])

    # Drop privileges for xdg-mime parts, so it updates the correct user

    # This works for xdg-open "mailto:"
    # Note that you may need to restart your browser, because several cache the mailto program.
    run_without_root(["xdg-mime", "default", DESKTOP_NAME, "x-scheme-handler/mailto"])

def parse_mailto(url):
    if url.startswith("mailto:"):
        url = url.removeprefix("mailto:")

    if "?" in url:
        to, url = url.split("?")
        d = {}
        for part in url.split("&"):
            k, v = part.split("=")
            d[k] = v
    else:
        to, d = url, {}

    return to, d

def make_url(to, kw):
    d = defaultdict(str, kw)
    d["to"] = to
    return WEBMAIL_URL.format_map(d)

def visit(url):
    browser = os.environ.get("BROWSER", DEFAULT_BROWSER)
    os.execvp(browser, [browser, url])

if __name__ == '__main__':
    if len(sys.argv) == 1 or sys.argv[1] in ("-h", "--help", "-help"):
        usage()
    elif sys.argv[1] == "--install":
        install()
    else:
        to, args = parse_mailto(sys.argv[1])
        url = make_url(to, args)
        visit(url)
