#!/bin/bash
if [ "$#" -ne "2" ]
then
    echo "Usage: `basename $0` NUM-POMODOROS DESC"
    exit 1
fi

curl --data "auth_token=9UTDTqdLanUbTZLD44qp&timestamp=$(date +%s)&value=$1&comment=$2" https://www.beeminder.com/api/v1/users/zacharyvance/goals/pomodoros/datapoints.json | tee -a ~/.pomodoro_history
echo | tee -a ~/.pomodoro_history
#echo "Pomodoro on $(date +%s): $1" | tee -a ~/.pomodoro_history
