#!/usr/bin/env python3
"""
tee-cmd: like tee, but prepends the command line invocation to the output file.

Usage: some_command | tee-cmd output.log

The output file will start with:
    $ some_command # 2025-01-10 14:32:01
    <stdout follows>

Author: Claude (Anthropic) with human collaboration
"""

import sys
import os
import datetime

def main():
    if len(sys.argv) != 2:
        print(f'usage: command | {sys.argv[0]} output.log', file=sys.stderr)
        sys.exit(1)
    
    out_path = sys.argv[1]
    
    # Try to get the full pipeline command
    # This is a bit hacky - we read /proc/self/fd/0's command if available
    cmdline = None
    try:
        # Get parent process command line
        ppid = os.getppid()
        with open(f'/proc/{ppid}/cmdline', 'rb') as f:
            cmdline = f.read().decode('utf-8', errors='replace').replace('\x00', ' ').strip()
    except:
        pass
    
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    with open(out_path, 'w') as out:
        if cmdline:
            out.write(f'$ {cmdline} # {timestamp}\n')
        else:
            out.write(f'$ ??? # {timestamp}\n')
        out.flush()
        
        for line in sys.stdin:
            sys.stdout.write(line)
            sys.stdout.flush()
            out.write(line)
            out.flush()

if __name__ == '__main__':
    main()
